### ISSUE TITLE
access to metadata

### ISSUE THREAD

**Issue by gmagnai** [younginnovations/resourcecontracts-api#16]
The returned index of metadata is:

"metadata" : {
          "type" : "**json**",
          "**value**" : "{\"contract_name\":\"\u0416\u0438\u0448\u044d\u044d \u0433\u044d\u0440\u044d\u044d\u043d\u0438\u0439 \u0437\u0430\u0433\u0432\u0430\u0440\",\"contract_identifier\":\"jg\",\"language\":\"mn\",\"country\":{\"code\":\"MN\",\"name\":\"Mongolia\"},\"resource\":[\"Alumina\"],\"government_entity\":[{\"entity\":\"\",\"identifier\":\"\"}],\"document_type\":\"Social Agreement\",\"type_of_contract\":[\"Agricultural Development Agreement\"],\"signature_date\":\"2016-04-27\",\"**signature_year**\":\"2016\",\"company\":[{\"name\":\"NRGI\",\"participation_share\":\"\",\"jurisdiction_of_incorporation\":\"\",\"registration_agency\":\"\",\"company_founding_date\":null,\"company_address\":\"\",\"company_number\":\"\",\"parent_company\":\"\",\"open_corporate_id\":\"\",\"operator\":\"-1\"}],\"project_title\":\"\",\"project_identifier\":\"\",\"concession\":[{\"license_name\":\"\",\"license_identifier\":\"\"}],\"source_url\":\"\",\"disclosure_mode\":\"\",\"date_retrieval\":null,\"category\":[\"rc\"],\"deal_number\":\"\",\"matrix_page\":\"\",\"contract_note\":\"\",\"is_supporting_document\":\"0\",\"annexes_missing\":\"-1\",\"pages_missing\":\"-1\",\"show_pdf_text\":\"1\",\"file_size\":1614889,\"open_contracting_id\":\"ocds-591adf-MN3111225135RC\",\"amla_url\":\"\",\"file_url\":\"https:\/\/s3.aws_region.amazonaws.com\/aws_bucker_name\/a7ab85d3381e7d5eb15ac91101fe43f38b4d2188.pdf\",\"word_file\":\"\"}"
        }

metadata has type and value. The code is accessing **signature_year** by metadata.signature_year but it's not working.

How can i access these metadata fields.

I'm using Elasticsearch 2.3, Logstash. 
Thank you.

**Comment by gmagnai** [comment]
Ah.. The metadata is string in my mapping.. There is a problem.

**Comment by gmagnai** [comment]
Hmmm. How to replace \" with empty?

**Comment by manishgs** [comment]
@gmagnai 

"\ " is for escaping why you want to replace?

You can decode the json like this.

$data = '{
"metadata" : {
"type" : "json",
"value" : "{\"contract_name\":\"\u0416\u0438\u0448\u044d\u044d \u0433\u044d\u0440\u044d\u044d\u043d\u0438\u0439 \u0437\u0430\u0433\u0432\u0430\u0440\",\"contract_identifier\":\"jg\",\"language\":\"mn\",\"country\":{\"code\":\"MN\",\"name\":\"Mongolia\"},\"resource\":[\"Alumina\"],\"government_entity\":[{\"entity\":\"\",\"identifier\":\"\"}],\"document_type\":\"Social Agreement\",\"type_of_contract\":[\"Agricultural Development Agreement\"],\"signature_date\":\"2016-04-27\",\"signature_year\":\"2016\",\"company\":[{\"name\":\"NRGI\",\"participation_share\":\"\",\"jurisdiction_of_incorporation\":\"\",\"registration_agency\":\"\",\"company_founding_date\":null,\"company_address\":\"\",\"company_number\":\"\",\"parent_company\":\"\",\"open_corporate_id\":\"\",\"operator\":\"-1\"}],\"project_title\":\"\",\"project_identifier\":\"\",\"concession\":[{\"license_name\":\"\",\"license_identifier\":\"\"}],\"source_url\":\"\",\"disclosure_mode\":\"\",\"date_retrieval\":null,\"category\":[\"rc\"],\"deal_number\":\"\",\"matrix_page\":\"\",\"contract_note\":\"\",\"is_supporting_document\":\"0\",\"annexes_missing\":\"-1\",\"pages_missing\":\"-1\",\"show_pdf_text\":\"1\",\"file_size\":1614889,\"open_contracting_id\":\"ocds-591adf-MN3111225135RC\",\"amla_url\":\"\",\"file_url\":\"https:\/\/s3.aws_region.amazonaws.com\/aws_bucker_name\/a7ab85d3381e7d5eb15ac91101fe43f38b4d2188.pdf\",\"word_file\":\"\"}"
}}';

$d = json_decode($data);
print_r($d);

**Comment by gmagnai** [comment]
@manishgs Thank you
If i were using elasticsearch 1.5 there is no problem. But elasticsearch version is now in 2.3. So decide to use newer version of elasticsearch. But elasticsearch 2.3 is rejected the river plugin. 
Possible way is to use Logstash. 
I can parse that output JSON in PHP. But I cant search query metadata in elasticsearch. Because JSON datatype is mapped by string by default config of Logstash.  
But I found some solutions and added some lines in my logstash config.

filter{
        ruby {
                code => "
                       require 'json'
                       metadata = JSON.parse(event['metadata'].to_s)
                       event['metadata'] = metadata
                "
       }
}

Then elasticsearch returns metadata by json object that is solved my problem.
Now output is:
        "metadata" : {
          "contract_name" : "Child of the contract Young Nepal",
          "contract_identifier" : "Nepal Government",
          "language" : "en",
          "country" : {
            "code" : "NP",
            "name" : "Nepal"
          },
          "resource" : [ "Coal", "Gold" ],
          "government_entity" : [ {
            "entity" : "",
            "identifier" : ""
          } ],
          "document_type" : "Contract",
          "type_of_contract" : [ "Joint Venture Agreement", "Service Contract" ],
          "signature_date" : "2015-09-02",
          "signature_year" : "2015",
          "company" : [ {
            "name" : "KUIKEL Enterprises",
            "participation_share" : "0.5",
            "jurisdiction_of_incorporation" : "DZ",
            "registration_agency" : "Registered to MAC",
            "company_founding_date" : "1993-02-16",
            "company_address" : "Banepa Nepal",
            "company_number" : "222",
            "parent_company" : "7digital",
            "open_corporate_id" : "https://www.google.com.np",
            "operator" : "-1"
          } ],
          "project_title" : "Project 1",
          "project_identifier" : "Ram404",
          "concession" : [ {
            "license_name" : "New Lisence",
            "license_identifier" : "Lis_no_4040"
          }

Finnally it's Okey now.
Thank you! :-) 
sorry about my bad english.
