### ISSUE TITLE
contract/attributes 'aggs' issue

### ISSUE THREAD

**Issue by magnaibayar** [younginnovations/resourcecontracts-api#17]
Hello. I have some problem about getting contract attributes. 
I have 2 contract and 2 company. The companies name are : "Epotecmass", "CC Mongolia".
But attributes gives me: "Epotecmass", "CC", "Mongolia"
And contract types same too..

Please, help me..

**Comment by manishgs** [comment]
Which Api endpoint are you referring? Please provide the response json.

**Comment by magnaibayar** [comment]
@manishgs Thank you for helping me.
In frontend API 'contract/attributes', here is JSON output of attributes.
{ "company_name": [ "\u0433\u043e\u0443\u043b\u0434\u0435\u043d", "\u043c\u043e\u043d\u0433\u043e\u043b\u0438\u0430", "\u0441\u0441", "\u044d\u0441\u0441\u044d\u043d\u0441" ], "corporate_grouping": [], "contract_type": [ "agreement", "and", "asset", "concession", "purchase", "sale" ], "document_type": [], "language": [ "en", "mn" ] }

In master index of elasticsearch output is:
"hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "resource_master",
      "_type" : "master",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "metadata" : {
          "contract_name" : "Жишээ гэрээ",
          "open_contracting_id" : "ocds-591adf-MN7286372716RC",
          "country_name" : "Mongolia",
          "country_code" : "MN",
          "signature_year" : "2016",
          "signature_date" : "2016-06-27",
          "resource" : [ null, "Acacia", "Aggregates" ],
          "file_size" : 182064,
          "language" : "mn",
          "category" : [ "rc" ],
          "contract_type" : [ "Asset Sale and Purchase Agreement" ],
          "document_type" : "Contract",
          "resource_raw" : [ null, "Acacia", "Aggregates" ],
          "show_pdf_text" : "1",
          "company_name" : [ "СС Монголиа" ],
          "corporate_grouping" : [ ]
        },
        "metadata_string" : " 2016-06-27 2016 MN Mongolia Acacia ..........................",
        "pdf_text_string" : "Админ модуль\n-\n\nБүртгэлийн үндсэн дээр .......................................",
        "annotations_category" : [ "Гэрээ" ],
        "annotations_string" : " Гэрээний үндсэн мэдээллийг тэмдэглэв."
      }
    }

**Comment by magnaibayar** [comment]
Also forget to say something. In document_type.raw is also empty. When i'm trying to get `document_type` is splitten strings like company_name.  
Someone told me You have to change "company_name" field in your mapping. field index from not_analyzed to analyzed or create raw field. I tried it but no changes. It's possible? 
When i have created raw field in company mapping, then publish all contracts and getting company_name.raw is empty result [].
Hmm, i spend too many hours in this problem but i didn't find any solutions. 
Sorry about my english. May be read and understand my issue is hard thing for you. I'm trying to learn english for better

**Comment by deepak-shah-np** [comment]
The default index value of string is "analyzed", which is splitted by space, slashes, dashes and many other character on aggregation.
So for these kind of field which is to be aggregated or exact matching need index value as "not_analyzed".

We have specified index value of string as per need .

> Someone told me You have to change "company_name" field in your mapping. field index from not_analyzed to analyzed or create raw field. I tried it but no changes. It's possible?

Yes, you have to change index value of "company_name" in mapping . Create a new index and type and run this mapping of respective type before populating with data. 

> When i have created raw field in company mapping, then publish all contracts and getting company_name.raw is empty result [].

Use this mapping for company name.

```
'company_name'  : {
    'type'   : 'string',
    "analyzer": "english",
    "fields"  : {
        "raw" : {
            "type" : "string",
            "index": "not_analyzed"
        }
    }
},
```

And use company_name.raw for aggregation or exact matching and company_name for search purpose.

If you are facing problem in aggregation and if you think there should be changes in mapping . Please provide the list  of field and type name .

Please do ask , if you still have any confusion.

**Comment by magnaibayar** [comment]
@hello-deepak 
Thank you very much! Solved!
