### ISSUE TITLE
`documentcloud_url` does not exists on all contract (especially those from PH)

### ISSUE THREAD

**Issue by jerico** [younginnovations/resourcecontracts-api#2]
Since view page of contract is still under development, I've opted to use Document Cloud's default viewer for the mean time. I plan to embed it as an `iframe` in the metadata view.

Question is: why does `documentcloud_url` only exists in limited contracts? Is it possible to add `documentcloud` keys on all contracts?

**Comment by anjesh** [comment]
Document Cloud url appears for the contracts which are migrated from previous document cloud system only, and was kept there to find the contracts that were migrated primarily for test/verification purpose. For all those that are added manually into the system won't have that. Infact documentcloud_url won't  be part of the metadata as well, it's just a hidden field, added during migration.

**Comment by jerico** [comment]
That clears it up. Thanks @anjesh
