### ISSUE TITLE
Contract 72 is showing on search result even if it's not published yet

### ISSUE THREAD

**Issue by jerico** [younginnovations/resourcecontracts-api#3]
![screen shot 2015-10-05 at 17 12 35](https://cloud.githubusercontent.com/assets/1062325/10276845/c2a37520-6b84-11e5-99c3-f6683b1d076c.png)

<img width="790" alt="screen shot 2015-10-05 at 16 59 31" src="https://cloud.githubusercontent.com/assets/1062325/10276853/cccf40a6-6b84-11e5-865f-83c06c76c3c8.png">

**Comment by anjesh** [comment]
It was published and then updated, so the state changed to Draft. You may see in the activity logs 

![image](https://cloud.githubusercontent.com/assets/120488/10277021/d2d7ac70-6b72-11e5-8661-3e39ee92c9cd.png)

**Comment by jerico** [comment]
If the state is `Draft`, should the contract still show on search results?

**Comment by anjesh** [comment]
Yes, the contract will still show after the metadata/annotation/text is updated after being published. You have to manually unpublish to remove from the Elasticsearch engine and then it will not be shown in the results.

**Comment by jerico** [comment]
This is fixed. Thanks
