### ISSUE TITLE
API endpoint is down?

### ISSUE THREAD

**Issue by jerico** [younginnovations/resourcecontracts-api#4]
Just to confirm if you did change the url of API or is it just down at the moment?

http://downforeveryoneorjustme.com/rc-elasticsearch.elasticbeanstalk.com

**Comment by anjesh** [comment]
Hi Jerico,

Can you use this IP http://54.173.9.19/ instead for now. We are looking
into the problem. It somehow didn't work for no reason.

Thanks
Anjesh.

**Comment by jerico** [comment]
Hi Anjesh, 

I overlooked this one and was not able to implement right away. 

I changed the API to use the API instead. It's working now.

Thanks,
Jerico
